name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77b357f1e949d6e7a7f43160fda8ac31007af7e859cabf4831af5211889c3ed4"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
