name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0bc205ae6b6fecaf03cd043ac280b7f80a34c9dc5d6025c22a030d4023add32"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
