name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6484fd59a49cda300087762bdc0bb8fe091fad84161b74cd8441da964de56539"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
