name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cb4756f8f838229bf14c257cb001e483fa7006ac5c5a7fe1ec884c1f730ea43"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
