name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6081dba616c87e2b13b12f84dfb2418a112563a89a983792e675c50d411e8a87"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
