name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe12e299504cd897fcbadc19080e94a6bf4402b19d5ca6d3a9e1404339338762"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
