name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b09f9e6f5c63f744c0fbbf0ae606860e800d25a02be9ae42362a1f6d2301cd1e"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
