name = "There Are So Many Fucking Dimensions and Bosses"
author = "TheWisme"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5039474cac05a1dfc8bf51bb76916cbfb608cf92247f90cc0cd815ad4bf48dcb"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
